<?php

    use Illuminate\Database\Seeder;
    
    class CreateReportsSeeder extends Seeder {
 
        public function run() {
            DB::table('reports')->insert(array(
                array('outlet_name'=>'Circle K', 'products'=>'Sari Roti', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-03 01:01:01'),
                array('outlet_name'=>'Circle K', 'products'=>'Equil', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-07 01:01:01'),
                array('outlet_name'=>'Circle K', 'products'=>'Sari Roti', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-03 01:01:01'),
                array('outlet_name'=>'Circle K', 'products'=>'Equil', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-07 01:01:01'),
                array('outlet_name'=>'Circle K', 'products'=>'Sari Roti', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-03 01:01:01'),
                array('outlet_name'=>'Circle K', 'products'=>'Equil', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-07 01:01:01'),
                array('outlet_name'=>'Circle K', 'products'=>'Sari Roti', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-03 01:01:01'),
                array('outlet_name'=>'Circle K', 'products'=>'Equil', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-07 01:01:01'),
                array('outlet_name'=>'Circle K', 'products'=>'Sari Roti', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-03 01:01:01'),
                array('outlet_name'=>'Circle K', 'products'=>'Equil', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-07 01:01:01'),
                array('outlet_name'=>'Circle K', 'products'=>'Sari Roti', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-03 01:01:01'),
                array('outlet_name'=>'Circle K', 'products'=>'Equil', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-07 01:01:01'),
                array('outlet_name'=>'Circle K', 'products'=>'Sari Roti', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-03 01:01:01'),
                array('outlet_name'=>'Circle K', 'products'=>'Equil', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-07 01:01:01'),
                array('outlet_name'=>'Circle K', 'products'=>'Sari Roti', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-03 01:01:01'),
                array('outlet_name'=>'Circle K', 'products'=>'Equil', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-07 01:01:01'),
                array('outlet_name'=>'Circle K', 'products'=>'Sari Roti', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-03 01:01:01'),
                array('outlet_name'=>'Circle K', 'products'=>'Equil', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-07 01:01:01'),
                array('outlet_name'=>'Circle K', 'products'=>'Sari Roti', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-03 01:01:01'),
                array('outlet_name'=>'Circle K', 'products'=>'Equil', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-07 01:01:01'),
                array('outlet_name'=>'Circle K', 'products'=>'Sari Roti', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-03 01:01:01'),
                array('outlet_name'=>'Circle K', 'products'=>'Equil', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-07 01:01:01'),
                array('outlet_name'=>'Circle K', 'products'=>'Sari Roti', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-03 01:01:01'),
                array('outlet_name'=>'Circle K', 'products'=>'Equil', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-07 01:01:01'),
                array('outlet_name'=>'Circle K', 'products'=>'Sari Roti', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-03 01:01:01'),
                array('outlet_name'=>'Circle K', 'products'=>'Equil', 'users_city'=>'Bekasi', 'age'=>'30', 'outlet_area'=>'Tebet', 'province'=>'DKI Jakarta', 'gender'=>'Male', 'usership'=>NULL, 'sec'=>NULL, 'outlet_type'=>'Convenience Store', 'created_at'=>'2017-01-03 01:01:01', 'updated_at'=>NULL, 'snap_at'=>'2017-01-07 01:01:01'),
            ));
        } 

    }